name: Build & Deploy Classifier

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.py'
      - 'requirements.txt'
      - 'Dockerfile'
      - '.github/workflows/classifier.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: docker.io/${{ secrets.DOCKER_USERNAME }}/classifier:latest

      - name: SSH Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e

            mkdir -p ~/classifier-data/keys

            # JSON 원문을 그대로 파일로 저장
            printf '%s' "${{ secrets.GCP_SA_JSON }}" > ~/classifier-data/keys/gcp.json

            # env 파일 생성
            {
              echo "MONGO_URI=${{ secrets.MONGO_URI }}";
              echo "GCS_BUCKET=zezeone_images";
              echo "GCS_SUBDIR=grade";
              echo "GOOGLE_APPLICATION_CREDENTIALS=/keys/gcp.json";
            } > ~/classifier-data/classifier.env

            docker pull docker.io/${{ secrets.DOCKER_USERNAME }}/classifier:latest
            docker stop classifier || true
            docker rm classifier || true

            docker run -d --name classifier \
              --network backend_app-network \
              --env-file ~/classifier-data/classifier.env \
              -v ~/classifier-data/keys/gcp.json:/keys/gcp.json:ro \
              -p 8100:8000 \
              docker.io/${{ secrets.DOCKER_USERNAME }}/classifier:latest
